{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pdsl-app.fullname" . }}
rules:
{{- range .Values.serviceAccount.rbac }}
  - apiGroups: {{ toJson .apiGroups }}
    resources: {{ toJson .resources }}
    verbs: {{ toJson .verbs }}
{{- end }}
{{- end }}
